### PR TITLE
Add GitHub actions for Mojito JS

### PR DESCRIPTION
**Pull request by kingo55**
This was pretty easy to pop together for #44 . 

One issue I had was with adding the `gulp new --aa a1` command - I thought it might be a good idea to add this as another test of sorts. But that [failed under Node 8.x](https://github.com/kingo55/mojito-js-delivery/commit/1ab6059429afc5edeb94b0ec777fb2df5b5268f1/checks?check_suite_id=379312718). Anyway, I figure we should have a more thorough gulp utils test suite as described on #47 .

Regardless, it works [fine across different versions of Node](https://github.com/kingo55/mojito-js-delivery/commit/fb7c938a21b7cbe4cb406d8ef94440bd554d4641/checks?check_suite_id=379315410).

Have you guys got any feedback on this issue or the Github Actions YML itself?

### CODE REVIEW

**Review by allmywant — APPROVED** [review]

**Comment by allmywant** [comment]
@kingo55 
I haven't got any feedback on this issue. From the error stack, it failed on below codes:

```
if (!fs.existsSync(waveFolder)) {
        fs.mkdirSync(waveFolder, { recursive: true });
    }
```
The node version on my end is 10.15.3, I can have a debug on 8.x if nesserary.

**Comment by kingo55** [comment]
@allmywant - thanks. I've only got v10 and v13 here too, so can't check it readily either.

Do lots of people use Node 8? I just used the default suggested Node versions from GitHub Actions.

Might be worth handling with the #47 test suite.

**Comment by kingo55** [comment]
@dapperdrop - did you have any comments on this PR?

**Review by dapperdrop — APPROVED** [review]

**Comment by dapperdrop** [comment]
No comments - looks good. Just approved.

**Pull request merged**
