### PR TITLE
Ensure multi observers on the same elements working as expected

### PR DESCRIPTION
**Pull request by allmywant**
This is an isssue I found when I was building tfes tests. If we have multi observers on the same elements, then only the callback function of the first observer will be fired. Originally, I had this check:

```
for (var j=0,jc=elements.length;j<jc;j++)
{
    // Skip observed elements
    if (elements[j]._observed)
    {
        continue;
    }

    elements[j]._observed = true;
    listener.fn(elements[j]);
}
```

Now I fixed it by assign an `index` to each observer and using it to check if an element is observed:

```
for (var j=0,jc=elements.length;j<jc;j++)
{
    // Skip observed elements
    if (elements[j]['_observed' + listener.index])
    {
        continue;
    }

    elements[j]['_observed' + listener.index] = true;
    listener.fn(elements[j]);
}
```

### CODE REVIEW

**Comment by kingo55** [comment]
Great catch, @allmywant - been checking this out this evening. Will let you know if I have any questions.

**Review by kingo55 — APPROVED** [review]
This looks great @allmywant! I think it is ready to merge.

**Comment by kingo55** [comment]
@dapperdrop - see what you think...

**Review by dapperdrop — APPROVED** [review]
Looks good @allmywant - nice work!

**Pull request merged**
