### PR TITLE
Bump packages 2021-06

### PR DESCRIPTION
**Pull request by kingo55**
@dapperdrop and @allmywant - Just updating the packages here.

Would you guys mind checking this out if you have a few minutes?

### CODE REVIEW

**Review by allmywant — APPROVED** [review]
@kingo55 
I made same changes here and all tests passed.

**Review by dapperdrop — APPROVED** [review]

**Comment by kingo55** [comment]
@allmywant - which changes did you end up making there? Looks like Node 8.x doesn't like the upgrades.

**Comment by allmywant** [comment]
> @allmywant - which changes did you end up making there? Looks like Node 8.x doesn't like the upgrades.

I just modified the package.json and bumped package versions exactly same as you did. I'm using Node 10.15.3, what errors you encountered on Node 8.x?

**Comment by kingo55** [comment]
Just this issue on `globby`:

https://github.com/kingo55/mojito-js-delivery/runs/2761038463

Every other version I've tested builds/runs it fine. Makes me wonder whether it's a real issue.

**Comment by allmywant** [comment]
It seems the ```del``` lib caused this issue, previously version was 5.1.0 and upgraded version is 6.0.0.
5.1.0 requires "globby": "10.0.2", 6.0.0 requires "globby": "^11.0.1". 
I think globby 11.x doesn't support Node 8.x, but they don't say that in https://github.com/sindresorhus/globby. 
For now, we can downgrade ```del``` to 5.1.0 to prevent this issue.

**Comment by kingo55** [comment]
Amazing. Thanks for that @allmywant - it's building on Node 8 once more...

**Pull request merged**
